version: '3'

# networks:
#     monitor:
#         driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./volumes/prometheus:/etc/prometheus:ro
      # - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # - ./volumes/prometheus/targets.yml:/etc/prometheus/targets.yml
      # - ./volumes/prometheus/catblackbox.yml:/etc/prometheus/catblackbox.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    # networks:
        #     - monitor

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.17.0
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./volumes/blackbox_exporter/blackbox.yml:/etc/prometheus/blackbox.yml:ro
    command:
      - --config.file=/etc/prometheus/blackbox.yml

    # networks:
    #     - monitor
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager 
    ports:
      - "9093:9093"
    volumes:
      - ./volumes/alertmanager/alertmanager.yml:/alertmanager-data/alertmanager.yml
    command:
      - --config.file=/alertmanager-data/alertmanager.yml
