alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 5s
  scrape_interval: 5s
rule_files:
- /etc/prometheus/catblackbox.yml
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- file_sd_configs:
  - files:
    - /etc/prometheus/http_200.yml
  job_name: http_200
  metrics_path: /probe
  params:
    module:
    - http_200
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - replacement: blackbox-exporter:9115
    target_label: __address__
- file_sd_configs:
  - files:
    - /etc/prometheus/http_403.yml
  job_name: http_403
  metrics_path: /probe
  params:
    module:
    - http_403
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - replacement: blackbox-exporter:9115
    target_label: __address__
