global:
  scrape_interval: 5s
  evaluation_interval: 5s
  
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/catblackbox.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]