- job_name: "{{httpcode}}"
  metrics_path: /probe
  params:
    module: ["{{httpcode}}"] # Look for a HTTP 200 response.
  file_sd_configs:
    - files: ["/etc/prometheus/{{httpcode}}.yml"]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115 # The blackbox exporter's real hostname:port.
